services:
  - type: web
    name: mk-universal-downloader
    env: node
    plan: free
    buildCommand: |
      npm install
      mkdir -p $HOME/bin
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o $HOME/bin/yt-dlp
      chmod +x $HOME/bin/yt-dlp
      $HOME/bin/yt-dlp --version
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
